name       : qt5-quickcontrols
version    : 5.15.2
release    : 24
source     :
    - git|https://invent.kde.org/qt/qt/qtquickcontrols.git : cf3f6d7fec824cdf01f9b329ab3b92b1c0e0a420
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-or-later
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt5 Quick Controls Module
description: |
    The Qt Quick Controls module provides a set of controls that can be used to build complete interfaces in Qt Quick.
builddeps  :
    - pkgconfig(Qt5Qml)
rundeps    :
    - qt5-graphicaleffects
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtquickcontrols.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
