name       : qt5-quickcontrols
version    : 5.11.1
release    : 11
source     :
    - https://mirrors.ocf.berkeley.edu/qt/official_releases/qt/5.11/5.11.1/submodules/qtquickcontrols-everywhere-src-5.11.1.tar.xz : baea7f59513ffade3f8041c1756722334b7d04245667fa8faaeace07a430c656
license    :
    - GFDL-1.3
    - GPL-2.0
    - GPL-3.0
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Quick Controls Module
description: |
    The Qt Quick Controls module provides a set of controls that can be used to build complete interfaces in Qt Quick.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
rundeps    :
    - qt5-graphicaleffects
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtquickcontrols.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
