name       : qt5-quickcontrols
version    : 5.6.2
release    : 1
source     :
    - http://download.qt.io/official_releases/qt/5.6/5.6.2/submodules/qtquickcontrols-opensource-src-5.6.2.tar.xz : 5ed0f2292be10222dfb1b57a05472798fd759279f65455d91c02ef4fb746102c
license    :
    - GFDL-1.3
    - GPL-2.0
    - GPL-3.0
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Quick Controls Module
description: |
    The Qt Quick Controls module provides a set of controls that can be used to build complete interfaces in Qt Quick.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
patterns   :
    - demos :
        /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtquickcontrols.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
