name       : qt5-quickcontrols
version    : 5.9.0
release    : 2
source     :
    - http://download.qt.io/official_releases/qt/5.9/5.9.0/submodules//qtquickcontrols-opensource-src-5.9.0.tar.xz : 173dfffeb20315dceedeb22c19812752c07e25916044be5444fe00522e1754fe
license    :
    - GFDL-1.3
    - GPL-2.0
    - GPL-3.0
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Quick Controls Module
description: |
    The Qt Quick Controls module provides a set of controls that can be used to build complete interfaces in Qt Quick.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtquickcontrols.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
