name       : qt5-quickcontrols
version    : 5.15.1
release    : 21
source     :
    - https://download.qt.io/official_releases/qt/5.15/5.15.1/submodules/qtquickcontrols-everywhere-src-5.15.1.tar.xz : 0172f88779305aae57f3842538e91361ae9bc5ca2275ee5ce9d455309f0f2c7e
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-or-later
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt5 Quick Controls Module
description: |
    The Qt Quick Controls module provides a set of controls that can be used to build complete interfaces in Qt Quick.
builddeps  :
    - pkgconfig(Qt5Qml)
rundeps    :
    - qt5-graphicaleffects
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtquickcontrols.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
